# Generated by Django 3.2.8 on 2021-10-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('link', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('discount', models.CharField(max_length=30)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('discount_start', models.DateField(db_index=True)),
                ('discount_end', models.DateField(db_index=True)),
            ],
        ),
    ]
