# Generated by Django 3.2.8 on 2021-10-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='mydb',
            options={'ordering': ['-discount'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterField(
            model_name='mydb',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание акции'),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='discount',
            field=models.CharField(max_length=30, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='discount_end',
            field=models.DateField(db_index=True, verbose_name='Конец действия скидки'),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='discount_start',
            field=models.DateField(db_index=True, verbose_name='Начало действия скидки'),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='store_name',
            field=models.CharField(max_length=50, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='mydb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubrics', verbose_name='Рубрика'),
        ),
    ]
